created new draft PR as it was easier than fixing conflicts in previous.
replicatedhq/helm-charts pull request #30
Opened 2023-04-12 19:20 UTC by drohnow

- Added statefulset and values.yaml files.
- Bumped version
- Updated docs & changelog

2023-04-12 19:28 UTC, chris-sanders commented on charts/replicated-library/README_CHANGELOG.md.gotmpl
>  ### [Unreleased]
```suggestion

```

2023-04-12 19:37 UTC, chris-sanders commented
Interesting looking at the values.yaml file this introduce several configurations that are specific to StatefulSets on the `app` object.

I think those are:
- serviceName
- persistentVolumeClaimTemplate
- something about the ClusterIP?

I'm just trying to figure out if this is the API we want for these. Having fields that only apply with another field is set, might be unavoidable but it feels strange.

For example, could you not define a volume under persistence and that just be used as a volumeClaimTemplate if the deployment it's mapped to is a Statefulset?

2023-04-12 20:21 UTC, chris-sanders commented
Ok after discussing in person I think this is where we landed.

Allow statefulSet specific configs on the app so users have access.

persistentVolumClaimTemplate will need to be configured for a StatefulSet most of the time (probably what a user wants).

- We'll look at adding some storage abstraction so you can map a volume to the app and that would then handle choosing if you need a PVC (deployment) or PVCT (statefulset) so that it's consistent and the users doesn't have to understand that distinction to get started. This is expected to be non breaking so we can do that investigation at a later time.

serviceName is a statefulSet specific config, and for now it's just set to the app name. We should follow up with a future function that finds the service name and automatically sets it for you otherwise it's easy to misconfigure.

The clsuterIP setting was my misunderstanding, we'll update the phrasing to show that setting a service cluster IP to "None" is how you configure headless it's not unique to statefulSets.

2023-04-13 14:11 UTC, diamonwiggins commented on charts/replicated-library/templates/lib/_statefulset.tpl
> +  serviceName:  {{- default (include "replicated-library.names.appname" .) ($values.serviceName) }}
I wouldn't be opposed, but it's only worth pointing out that it _technically_ isn't a required field as I think you can use a non headless service with a StatefulSet if you wanted to where you could just leave `serviceName` blank. I think most would use a headless service, but not sure if that's enough of a caveat where we would want it to not be required.

2023-04-13 14:28 UTC, chris-sanders commented on charts/replicated-library/templates/lib/_statefulset.tpl
> +  serviceName:  {{- default (include "replicated-library.names.appname" .) ($values.serviceName) }}
Oh that's a good point, I was thinking it was required but it's not. If you _do_ set this and it doesn't match the actual service name is that an error? Now I'm questioning if I understand the impact of us 'guessing wrong' in this case. Maybe this is actually fine.

2023-04-14 00:34 UTC, chris-sanders requested changes
Is this the correct branch, I see a few errors in here in particular the indention of the metadat field is missing the `template` key which as far as I can tell means this will never properly work as written.

2023-04-14 00:34 UTC, chris-sanders commented on charts/replicated-library/templates/lib/_statefulset.tpl
> +    metadata:
This doesn't appear to be a valid format.
metadata is not a subfield of serviceName I think you've missed a key here somewhere.

2023-04-14 00:34 UTC, chris-sanders commented on charts/replicated-library/templates/lib/_statefulset.tpl
> +  volumeClaimTemplates:
I don't think volumeClaimTemplates are mandatory should this be behind an if statement?

2023-04-14 00:34 UTC, chris-sanders commented on charts/replicated-library/templates/lib/_statefulset.tpl
> +  serviceName:  {{- default (include "replicated-library.names.appname" .) ($values.serviceName) }}
I'll do further testing, but I think the leading "-" here is a problem. this is going to lave no space between the ":" and the value which isn't valid. I think.

I'm doing some testing I'll confirm this while I am.

2023-04-14 13:02 UTC, chris-sanders commented
I've opened #31 to fix the errors listed above it was more involved than I could do directly on this PR. (The PR merges into this branch).

I think there's still a discussion to be had around the format of the persistentVolumeClaimTemplate api that was added, I've detailed that in #31

2023-04-19 22:51 UTC, chris-sanders commented
I'm going to close this since #40 which was based on this landed.

2023-04-19 22:51 UTC, closed without merging