Fix: Containers/InitContainers
replicatedhq/helm-charts pull request #75
Opened 2023-05-15 21:36 UTC by diamonwiggins

* Fixes a bug that resulted in charts failing to render when multiple containers were configured on a single app

2023-05-15 22:02 UTC, chris-sanders requested changes
I haven't had time to dig through all of this, but just removing the end line chomping will likely solve the problem without leaving random spaces throughout the template. Can you try this with just the beginning and not the end `-` and see if that works?

2023-05-15 22:02 UTC, chris-sanders commented on charts/replicated-library/templates/lib/_container.tpl
> +{{ end }}
```suggestion
{{- end }}
```

2023-05-15 22:02 UTC, chris-sanders commented on charts/replicated-library/templates/lib/_container.tpl
> +{{ range $containerName, $containerValues := $values.containers }}
```suggestion
{{- range $containerName, $containerValues := $values.containers }}
```

2023-05-15 22:02 UTC, chris-sanders commented on charts/replicated-library/templates/lib/_init_container.tpl
> +{{ range $containerName, $containerValues := $values.initContainers }}
```suggestion
{{- range $containerName, $containerValues := $values.initContainers }}
```

2023-05-15 22:02 UTC, chris-sanders commented on charts/replicated-library/templates/lib/_init_container.tpl
> +{{ end }}
```suggestion
{{- end }}
```

2023-05-16 16:53 UTC, chris-sanders approved these changes
Great looks good to me. Generally speaking leading `-` are most of the time ok and trailing `-` are bad news unless it's purely logic. This reads more like I would expect to see it, if it's working for you I don't need more testing on other ways it could be written.

2023-05-16 16:54 UTC, diamonwiggins commented
> Great looks good to me. Generally speaking leading `-` are most of the time ok and trailing `-` are bad news unless it's purely logic. This reads more like I would expect to see it, if it's working for you I don't need more testing on other ways it could be written.

Yup, makes sense. I probably need to do a second pass of the chart to make things consistent here and ensure I don't have other bugs.

2023-05-16 16:54 UTC, merged